linters:
  enable-all: true
  disable:
    - gofumpt
    - varcheck
    - nosnakecase
    - interfacer
    - scopelint
    - exhaustivestruct
    - maligned
    - structcheck
    - ifshort
    - deadcode
    - golint
    - depguard
    - wsl
    - wrapcheck
    - exhaustruct
    - godox

linters-settings:
  cyclop:
    max-complexity: 15
