linters:
  enable-all: true
  disable:
    - gofumpt
    - depguard
    - wsl
    - wrapcheck
    - exhaustruct
    - execinquery
    - gomnd
    - varnamelen
    - godox

linters-settings:
  cyclop:
    max-complexity: 15
